services:
  webpi:
    extends:
      file: docker-compose.yml
      service: web
    build:
      args:
        IMAGE: "python:3.8.13"
        STAGING_VARIANT: "-buster"
        VARIANT: "-buster"
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

volumes:
  postgres_data: