services:
  webpi:
    extends:
      file: docker-compose.yml
      service: web
    build:
      args:
        IMAGE: "python:3.8.13"
        STAGING_VARIANT: "${WEBPI_IMAGE_STAGING_VARIANT:-buster}"
        VARIANT: "${WEBPI_IMAGE_VARIANT:-buster}"
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

volumes:
  postgres_data: